format_version: 2
pipelines:
  Backend_CommitPhase:
    group: SamplePipeline
    materials:
      backend:
        git: http://git-repo:3000/gogs/sample-pipeline-backend.git
        branch: master
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Build:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - ./scripts/commit/build.sh
