format_version: 2
pipelines:
  Backend_DevDeployment:
    group: SamplePipeline
    materials:
      backend:
        git: https://github.com/kumardevanmaha/booksapp
        branch: master
     
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Java_Build:
              tasks:
                - exec:
                   - mvn compile
                   - mvn package
                    
